### ISSUE TITLE
Crosscutting project ?

### ISSUE THREAD

**Issue by Kris-I** [Jadhielv/ITL#202]
Hello,

I need to use some enums in Application or Domain, it's not a good idea to create a crosscutting project to place these enums ? Same for exceptions, in Application you can throw an exception catched in the Middleware in the API.

Thanks,

**Comment by nminaya** [comment]
@Kris-I Hey, I think you should place your enums in the Domain project. The issue here is that currently not all the projects are referencing the Domain. But that can be fixed.

**Comment by Kris-I** [comment]
Sur you can reference the Domain but is that match with clean architecture ?
