### ISSUE TITLE
Migrate from .NET 7.0 to 8.0

### ISSUE THREAD

**Issue by Jadhielv** [Jadhielv/ITL#562]
[.NET 8](https://devblogs.microsoft.com/dotnet/announcing-dotnet-8/)

![image](https://github.com/user-attachments/assets/e644edda-ebbe-4f54-81b9-0dc758e4abab)

[Migrate from ASP.NET Core in .NET 7 to .NET 8](https://learn.microsoft.com/en-us/aspnet/core/migration/70-80?view=aspnetcore-7.0&tabs=visual-studio)

![image](https://github.com/user-attachments/assets/96389e9c-29f0-4bab-be06-9cc733dd0343)

**Comment by umardevX** [comment]
@Jadhielv Can you assign it to me?
